// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrdupojfgUWVAzOMjWndlh_W28oLB-WoU',
    appId: '1:438762959071:web:61dc06190be8389ac9b96a',
    messagingSenderId: '438762959071',
    projectId: 'project02-90a40',
    authDomain: 'project02-90a40.firebaseapp.com',
    storageBucket: 'project02-90a40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5u-vOzUrvHNIrd7BU7tCAIYXnSN4L6os',
    appId: '1:438762959071:android:d295f28baa64722cc9b96a',
    messagingSenderId: '438762959071',
    projectId: 'project02-90a40',
    storageBucket: 'project02-90a40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqB9b7o_66BK45giDV5mLG5U9Zok67zCw',
    appId: '1:438762959071:ios:2c1baead7a08eecdc9b96a',
    messagingSenderId: '438762959071',
    projectId: 'project02-90a40',
    storageBucket: 'project02-90a40.firebasestorage.app',
    iosBundleId: 'com.example.parkit02',
  );

}